### ISSUE TITLE
Рефакторинг авторизации

### ISSUE THREAD

**Issue by evgrezanov** [evgrezanov/bonus-plus-wp#47]
# TODO
- [x] Поле _дата рождения_ делаем не обязательным
- [x] Создаем end-point для запроса [GET /customer](https://bonusplus.pro/api/Help/Api/GET-customer_id_ean_phone) которая возвращает либо информацию о существующем клиенте, либо ошибку
- [x] Рефакторинг функции **bpwp_customer_login** добавляем вызов end-point
- [x] Создаем end-point для запроса [POST /customer](https://bonusplus.pro/api/Help/Api/POST-customer) для создания нового пользователя
- [x] переписать код отправки и подтверждения OTP https://idehweb.com/product/login-with-phone-number-in-wordpress/
- [x] выпилить весь ненужный код
