### ISSUE TITLE
Версия 2.8 - требования

### ISSUE THREAD

**Issue by evgrezanov** [evgrezanov/bonus-plus-wp#53]
## Требования

- [x] Рефакторинг авторизации #47 ё
- [x] #42 
- [x] Проверить баг с 2м списанием бонусов #40 
- [x] #56 
- [x] Исправлена проблема с безопастностью при генерации QR кода в личном кабинете #21 
- [x] убрать дату рождения #58

**Comment by yurovigorr** [comment]
Очень ждем решения #40
